const MIN_GROUP_PARTICIPANTS = 3;
const MAX_GROUP_PARTICIPANTS = 100;

const MIN_GROUP_NAME_LENGTH = 1;
const MAX_GROUP_NAME_LENGTH = 50;

module.exports = {
    MIN_GROUP_PARTICIPANTS,
    MAX_GROUP_PARTICIPANTS,
    MIN_GROUP_NAME_LENGTH,
    MAX_GROUP_NAME_LENGTH,
};